import 'package:json_annotation/json_annotation.dart';

part 'user_dto.g.dart';

/// Data Transfer Object for the user profile response from the API.
///
/// Annotated with [JsonSerializable] so that [_$UserDtoFromJson] and
/// [_$UserDtoToJson] are generated by `build_runner`.
@JsonSerializable()
class UserDto {

  final int id;
  final String username;

  final List<String> roles;

  /// Creates a [UserDto].
  const UserDto({
    required this.id,
    required this.username,
    required this.roles,
  });

  /// Deserialises a [UserDto] from a JSON map.
  factory UserDto.fromJson(Map<String, dynamic> json) =>
      _$UserDtoFromJson(json);

  /// Serialises this [UserDto] to a JSON map.
  Map<String, dynamic> toJson() => _$UserDtoToJson(this);
}
